### ISSUE TITLE
Implement module for import IES files ?

### ISSUE THREAD

**Issue by Lokotito** [cagrin/QLumEdit#1]
Really nice program to work with .LDT files, but I,m wondering if is posible to implement .IES import module? .IES is a text plain photo-metric file similar like .LDT file.

**Comment by cagrin** [comment]
Thanks, @Lokotito. QLumEdit was always only .LDT editor, but why not extend it? What would you like to do with .IES files?

**Comment by Lokotito** [comment]
> Thanks, @Lokotito. QLumEdit was always only .LDT editor, but why not extend it? What would you like to do with .IES files?

The first thing is open it and check all data (like QLumedit does with .LDT file now).

But will be very useful (if posible) let user to rotate photometry, sometimes (I don't know why) some programs interprets/draw a polar diagram from an .IES file in 90 degrees rotated, this is notable in street luminaries. I will try to share a .IES file with this issue from a manufacturer I know.

An of course save/export this .IES files to .LDT also, like QLumEdit does from .LDT to .IES.

Thanks for answer.
